#!/usr/bin/env bash
#
# setup_badkernel.sh
# Clone BadKernel from BashSQ/Bad-Kernel and integrate into Xcode project.
# Runs on GitHub Actions macOS runner.
#

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
BADKERNEL_REPO="${BADKERNEL_REPO:-https://github.com/BashSQ/Bad-Kernel.git}"
BADKERNEL_SRC="$ROOT/ExternalNoelx/BadKernel"
BADKERNEL_STUB_M="$ROOT/ExternalNoelx/BadKernel.m"
BADKERNEL_STUB_H="$ROOT/ExternalNoelx/BadKernel.h"

echo "═══════════════════════════════════════════════════════════"
echo "  BadKernel Setup (CI mode)"
echo "═══════════════════════════════════════════════════════════"
echo "  Repo: $BADKERNEL_REPO"
echo "  Dest: $BADKERNEL_SRC"
echo "───────────────────────────────────────────────────────────"

# ═══ 1. Clone repo ═══
TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/BadKernel.XXXXXX")"
trap 'rm -rf "$TEMP_DIR"' EXIT

echo "▶ Cloning BadKernel..."
if ! git clone --depth 1 "$BADKERNEL_REPO" "$TEMP_DIR/Bad-Kernel" 2>&1; then
    echo "❌ Failed to clone $BADKERNEL_REPO"
    exit 1
fi

CLONE_DIR="$TEMP_DIR/Bad-Kernel"

# ═══ 2. Verify structure ═══
echo "▶ Repo structure:"
echo "  BadKernel/:"
ls -la "$CLONE_DIR/BadKernel/" 2>/dev/null || echo "    NOT FOUND"
echo "  headers/:"
ls -la "$CLONE_DIR/headers/" 2>/dev/null || echo "    NOT FOUND"

if [ ! -d "$CLONE_DIR/BadKernel" ]; then
    echo "❌ BadKernel/ folder not found."
    exit 1
fi

# ═══ 3. Prepare destination ═══
mkdir -p "$BADKERNEL_SRC"
mkdir -p "$BADKERNEL_SRC/include"

# ═══ 4. Copy SOURCE (.m, .c) dari BadKernel/ ═══
echo "▶ Copying source files..."
find "$CLONE_DIR/BadKernel" -maxdepth 1 -type f \( -name "*.m" -o -name "*.c" \) -exec cp {} "$BADKERNEL_SRC/" \;

# ═══ 5. Copy HEADERS (.h) dari headers/ ═══
if [ -d "$CLONE_DIR/headers" ]; then
    echo "▶ Copying header files from headers/..."
    find "$CLONE_DIR/headers" -maxdepth 1 -type f \( -name "*.h" \) -exec cp {} "$BADKERNEL_SRC/" \;
    find "$CLONE_DIR/headers" -maxdepth 1 -type f \( -name "*.h" \) -exec cp {} "$BADKERNEL_SRC/include/" \;
fi

# ═══ 6. Copy HEADERS (.h) dari BadKernel/ juga (kalau ada) ═══
find "$CLONE_DIR/BadKernel" -maxdepth 1 -type f -name "*.h" -exec cp {} "$BADKERNEL_SRC/" \;
find "$CLONE_DIR/BadKernel" -maxdepth 1 -type f -name "*.h" -exec cp {} "$BADKERNEL_SRC/include/" \;

# ═══ 7. Cari BadKernel.h & BadKernel.m di mana aja ═══
find "$CLONE_DIR" -name "BadKernel.h" -exec cp {} "$BADKERNEL_SRC/" \; 2>/dev/null || true
find "$CLONE_DIR" -name "BadKernel.m" -exec cp {} "$BADKERNEL_SRC/" \; 2>/dev/null || true

echo "  Files di $BADKERNEL_SRC:"
ls -la "$BADKERNEL_SRC/" | tail -n +2 | awk '{print "    " $NF}'

# ═══ 8. Verify BadKernel.m & .h ═══
REAL_M="$BADKERNEL_SRC/BadKernel.m"

if [ ! -f "$REAL_M" ]; then
    echo "❌ BadKernel.m not found!"
    find "$CLONE_DIR" -type f -name "*.m"
    exit 1
fi

# Cek header
if [ -f "$BADKERNEL_SRC/BadKernel.h" ]; then
    echo "  ✅ BadKernel.h found in BadKernel/ folder"
    REAL_H="$BADKERNEL_SRC/BadKernel.h"
elif [ -f "$BADKERNEL_STUB_H" ]; then
    echo "  ⚠️  BadKernel.h not in cloned repo, using stub header"
    REAL_H="$BADKERNEL_STUB_H"
else
    echo "  ⚠️  No BadKernel.h anywhere, will try to compile without"
    REAL_H=""
fi

# ═══ 9. Replace stub BadKernel.m dengan asli ═══
echo "▶ Replacing stub files..."

if [ -f "$BADKERNEL_STUB_M" ]; then
    cp "$BADKERNEL_STUB_M" "$BADKERNEL_STUB_M.stub.bak"
    echo "  Stub backup → BadKernel.m.stub.bak"
fi

cp "$REAL_M" "$BADKERNEL_STUB_M"
echo "  ✅ BadKernel.m → replaced with real implementation"

# Replace header (kalau ada)
if [ -n "$REAL_H" ] && [ "$REAL_H" != "$BADKERNEL_STUB_H" ] && [ -f "$REAL_H" ]; then
    cp "$REAL_H" "$BADKERNEL_STUB_H"
    echo "  ✅ BadKernel.h → replaced"
fi

# ═══ 10. Copy headers ke include/ juga ═══
if [ -f "$BADKERNEL_STUB_H" ]; then
    cp "$BADKERNEL_STUB_H" "$BADKERNEL_SRC/include/BadKernel.h"
fi

# ═══ 11. Bikin BADKERNEL_REAL define header ═══
cat > "$BADKERNEL_SRC/BadKernel-Real.h" << 'EOF'
// Auto-generated by setup_badkernel.sh
#ifndef BADKERNEL_REAL
#define BADKERNEL_REAL 1
#endif
EOF

# ═══ 12. Summary ═══
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  ✅ BadKernel Setup Complete"
echo "═══════════════════════════════════════════════════════════"
echo "  Real .m: $BADKERNEL_STUB_M"
echo "  Header:  $BADKERNEL_STUB_H"
echo ""
echo "  Files di $BADKERNEL_SRC:"
ls -la "$BADKERNEL_SRC/" | tail -n +2 | awk '{print "    " $NF}'
echo ""
echo "  Next: run ./build_universal.sh"
echo "═══════════════════════════════════════════════════════════"
