name: Build IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: List root directory
        run: ls -la
      - name: Make script executable
        run: chmod +x build_unsigned.sh
      - name: Build IPA
        run: ./build_unsigned.sh 2>&1 | tee build.log
      - name: Upload IPA artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-IPA
          path: build/*.ipa
      - name: Upload build log (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Log
          path: build.log
